version: '3.9'
services:
  jekyll:
    build:
      context: .
    volumes:
      - .:/jekyll:cached
      - gem-local:/usr/local/bundle
    ports:
      - 4000:4000

volumes:
  gem-local:
    driver: "local"
